Work on Frontal Melt Coupler
Compilation breaks with

/Users/andy/pism/src/icemodel/calving.cc:49:34: error: use of undeclared identifier 'm_frontalmelt'
  inputs.frontal_melt_rate    = &m_frontalmelt->frontal_melt_rate();
                                 ^
1 error generated.
make[2]: *** [src/CMakeFiles/pism.dir/icemodel/calving.cc.o] Error 1
make[1]: *** [src/CMakeFiles/pism.dir/all] Error 2

How can I get access to frontal_melt_rate() which is in coupler/FrontalMeltModel.hh?